import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Load playbooks securely
let playbooks = {};
try {
  const data = fs.readFileSync(path.join(__dirname, 'playbooks.json'), 'utf8');
  playbooks = JSON.parse(data);
} catch (error) {
  console.error("Failed to read playbooks.json:", error);
}

/**
 * Validates the Gemini Agent's recommendation against the deterministic playbook.
 * If details match, it approves. If there is a mismatch or hallucination, it overrides.
 * 
 * @param {string} playbookKey - The key in playbooks.json (e.g. MEDICAL_SECTOR_102)
 * @param {string} llmOutput - The raw text generated by the agent
 * @returns {object} An object containing { verifiedOutput, status, changesMade, details }
 */
export function verifyIncidentRecommendation(playbookKey, llmOutput) {
  let normalizedKey = (playbookKey || '').trim().toUpperCase();

  // 1. Normalize connectors (" at ", " - ", ":") to spaces/underscores
  normalizedKey = normalizedKey.replace(/\s+AT\s+/g, ' ');
  normalizedKey = normalizedKey.replace(/\s*-\s*/g, ' ');
  normalizedKey = normalizedKey.replace(/\s*:\s*/g, ' ');
  normalizedKey = normalizedKey.replace(/[\s_]+/g, '_');

  // Remap food court short layouts directly
  if (normalizedKey.includes('FOOD_COURT_ZONE_B') && !normalizedKey.includes('OVERFLOW')) {
    normalizedKey = 'FOOD_COURT_OVERFLOW_ZONE_B';
  } else if (normalizedKey.includes('FOOD_COURT_ZONE_A') && !normalizedKey.includes('OVERFLOW')) {
    normalizedKey = 'FOOD_COURT_OVERFLOW_ZONE_A';
  }

  // 2. If not a direct match, parse and reconstruct <TYPE>_<LOCATION>
  if (!playbooks[normalizedKey]) {
    const knownTypes = [
      'WATER_SHORTAGE',
      'WASHROOM_CONGESTION',
      'GATE_OVERFLOW',
      'FOOD_COURT_OVERFLOW',
      'WEATHER_ALERT',
      'MEDICAL_EMERGENCY'
    ];

    const knownLocations = [
      'SECTOR_310',
      'SECTOR_102',
      'SECTOR_205',
      'WASHROOM_SOUTH',
      'WASHROOM_EAST',
      'WASHROOM_WEST',
      'WASHROOM_NORTH',
      'GATE_A',
      'GATE_B',
      'GATE_C',
      'GATE_D',
      'FOOD_COURT_ZONE_A',
      'FOOD_COURT_ZONE_B',
      'SECTOR_ALL'
    ];

    let foundType = knownTypes.find(t => normalizedKey.includes(t));
    if (!foundType) {
      if (normalizedKey.includes('MEDICAL')) foundType = 'MEDICAL_EMERGENCY';
      else if (normalizedKey.includes('WEATHER')) foundType = 'WEATHER_ALERT';
      else if (normalizedKey.includes('FOOD_COURT')) foundType = 'FOOD_COURT_OVERFLOW';
      else if (normalizedKey.includes('GATE')) foundType = 'GATE_OVERFLOW';
      else if (normalizedKey.includes('WASHROOM')) foundType = 'WASHROOM_CONGESTION';
      else if (normalizedKey.includes('WATER')) foundType = 'WATER_SHORTAGE';
    }

    let foundLocation = knownLocations.find(loc => {
      if (loc === 'FOOD_COURT_ZONE_A') {
        return normalizedKey.includes('FOOD_COURT_ZONE_A') || normalizedKey.includes('ZONE_A');
      }
      if (loc === 'FOOD_COURT_ZONE_B') {
        return normalizedKey.includes('FOOD_COURT_ZONE_B') || normalizedKey.includes('ZONE_B');
      }
      if (loc === 'WASHROOM_SOUTH') {
        return normalizedKey.includes('WASHROOM_SOUTH') || (normalizedKey.includes('WASHROOM') && normalizedKey.includes('SOUTH'));
      }
      if (loc === 'WASHROOM_EAST') {
        return normalizedKey.includes('WASHROOM_EAST') || (normalizedKey.includes('WASHROOM') && normalizedKey.includes('EAST'));
      }
      if (loc === 'WASHROOM_WEST') {
        return normalizedKey.includes('WASHROOM_WEST') || normalizedKey.includes('WASHROOM_NORTH') || (normalizedKey.includes('WASHROOM') && (normalizedKey.includes('WEST') || normalizedKey.includes('NORTH')));
      }
      return normalizedKey.includes(loc);
    });

    if (!foundLocation && foundType === 'WEATHER_ALERT') {
      foundLocation = 'SECTOR_ALL';
    }

    if (foundType && foundLocation) {
      normalizedKey = `${foundType}_${foundLocation}`;
    }
  }

  const playbook = playbooks[normalizedKey];

  // If no playbook is defined for this incident type/zone, return as passed but warning
  if (!playbook) {
    return {
      verifiedOutput: llmOutput,
      status: 'PASSED_NO_PLAYBOOK',
      changesMade: false,
      details: {
        message: `No playbook configured for key "${normalizedKey}".`
      }
    };
  }

  const { primary_response_facility, room_number, evacuation_route, dispatch_squad } = playbook;

  // Check if LLM output mentions incorrect facilities/rooms/routes/squads
  // To identify hallucinations, we can look for numbers, rooms, exits, squads that don't match the playbook
  let isHallucinated = false;
  const discrepancies = [];

  // Helper check: does the output contain the required text verbatim? (Case insensitive check)
  const containsFacility = llmOutput.toLowerCase().includes(primary_response_facility.toLowerCase());
  const containsRoom = llmOutput.toLowerCase().includes(room_number.toLowerCase());
  const containsRoute = llmOutput.toLowerCase().includes(evacuation_route.toLowerCase());
  const containsSquad = llmOutput.toLowerCase().includes(dispatch_squad.toLowerCase());

  if (!containsFacility) {
    isHallucinated = true;
    discrepancies.push(`Missing or incorrect facility reference: Expected "${primary_response_facility}"`);
  }
  if (!containsRoom) {
    isHallucinated = true;
    discrepancies.push(`Missing or incorrect room layout info: Expected "${room_number}"`);
  }
  if (!containsRoute) {
    isHallucinated = true;
    discrepancies.push(`Missing or incorrect evacuation routing: Expected "${evacuation_route}"`);
  }
  if (!containsSquad) {
    isHallucinated = true;
    discrepancies.push(`Missing or incorrect dispatch team: Expected "${dispatch_squad}"`);
  }

  // Also check for aggressive pattern mismatch (e.g. if the LLM invents other rooms or squads)
  // Let's check for any mention of another room (e.g. "Room [0-9][A-Z]") that does not match
  const roomPattern = /Room \d[A-Z]-[Level\s\d]+/gi;
  const matches = llmOutput.match(roomPattern);
  if (matches) {
    for (const match of matches) {
      if (!match.toLowerCase().includes(room_number.toLowerCase())) {
        isHallucinated = true;
        discrepancies.push(`Hallucination detected: Output references "${match}" instead of "${room_number}"`);
      }
    }
  }

  if (isHallucinated) {
    // Generate the overriden safe output
    const safeOutput = `[🛡️ VERIFIED CRITICAL ALERT - ${normalizedKey}] Incident logged in stadium digital twin.

Emergency Protocol Initiated:
- Primary Destination: ${primary_response_facility} (${room_number})
- Evacuation Route: ${evacuation_route}
- Action Plan: Dispatch ${dispatch_squad} immediately to coordinates. Ground staff must secure the area and ensure the evacuation corridor is kept clear.

Data Integrity Status: Auto-Corrected via Deterministic System Playbook v1.02. Hallucination Risk: 0%.`;

    return {
      verifiedOutput: safeOutput,
      status: 'OVERRIDDEN',
      changesMade: true,
      details: {
        discrepancies,
        playbookUsed: playbook,
        originalOutput: llmOutput
      }
    };
  }

  // If correct, print verified banner
  const verifiedOutput = `[🛡️ VERIFIED CRITICAL ALERT - ${normalizedKey}]
${llmOutput}

Data Integrity Status: Validated via Deterministic System Playbook v1.02. Hallucination Risk: 0%.`;

  return {
    verifiedOutput,
    status: 'PASSED',
    changesMade: false,
    details: {
      playbookUsed: playbook
    }
  };
}
